/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DFS studio (https://sketchfab.com/DFS_studio)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cs-go-bomb-ca6b5adeeda647a9ac40f09dde162500
title: Cs Go Bomb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/bomb/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Armature" position={[0.01, -0.35, 1.62]}>
              <primitive object={nodes.Armature_rootJoint} />
              <group name="Cube001" position={[0.04, 0.15, 0.08]} rotation={[0, 0, 0.04]} scale={[1.4, 0.06, 0.61]}>
                <mesh name="Cube001_3" geometry={nodes.Cube001_3.geometry} material={materials['Material.008']} />
              </group>
              <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.blinker} skeleton={nodes.Cube001_1.skeleton} />
              <skinnedMesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials['Material.009']} skeleton={nodes.Cube001_2.skeleton} />
            </group>
            <group name="Plane" position={[-1.43, -3.53, 1]} scale={0.4}>
              <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials.Material} />
            </group>
            <group name="Plane001" position={[-0.3, 1.29, 2.06]} scale={0.99}>
              <mesh name="Plane001_0" geometry={nodes.Plane001_0.geometry} material={materials['Material.002']} />
            </group>
            <group name="Plane003" position={[2.23, -3.44, 0.93]} scale={0.35}>
              <mesh name="Plane003_0" geometry={nodes.Plane003_0.geometry} material={materials['Material.003']} />
            </group>
            <group name="Plane004" position={[-2.32, 0.1, 1.36]} scale={0.21}>
              <mesh name="Plane004_0" geometry={nodes.Plane004_0.geometry} material={materials['Material.010']} />
            </group>
            <group name="Plane005" position={[-2.22, 1.91, 2.13]} rotation={[-2.34, -1.55, 2.63]} scale={[0.14, 0.13, 0.13]}>
              <mesh name="Plane005_0" geometry={nodes.Plane005_0.geometry} material={materials['Material.011']} />
            </group>
            <group name="Plane010" position={[-1.3, 3.18, 1.63]} scale={0.3}>
              <mesh name="Plane010_0" geometry={nodes.Plane010_0.geometry} material={materials['Material.005']} />
            </group>
            <group name="Cylinder002" position={[1.34, 2.81, 1.5]} rotation={[1.62, 0, 0]} scale={[0.11, 0.11, 0.14]}>
              <mesh name="Cylinder002_0" geometry={nodes.Cylinder002_0.geometry} material={materials['Material.004']} />
            </group>
            <group name="Plane011" position={[0.51, 3.45, 1.59]} scale={0.29}>
              <mesh name="Plane011_0" geometry={nodes.Plane011_0.geometry} material={materials['Material.006']} />
            </group>
            <group name="Plane012" position={[1.33, 3.33, 1.53]} scale={0.18}>
              <mesh name="Plane012_0" geometry={nodes.Plane012_0.geometry} material={materials['Material.007']} />
            </group>
            <group name="Plane002" position={[-1.01, -0.49, 2.32]} scale={0.12}>
              <mesh name="Plane002_0" geometry={nodes.Plane002_0.geometry} material={materials['Material.012']} />
              <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials['Material.013']} />
            </group>
            <group name="Point" position={[-0.06, 0.52, 10.72]} rotation={[0.46, 0.47, 0.76]}>
              <group name="Point_1" />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
